name: auto-release-beta
on:
  pull_request:
      branches:
        - beta
      types: [closed]
jobs:
    build:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 📦 INSTALANDO NODEJS LTS
        uses: ./.github/actions/setup-node

      - name: ✏️ CONFIGURACIONES PARA FIRMAR COMMITS
        uses: ./.github/actions/git-config
        with:
          username: "Jmendez-Bot"
          email: "jorge.mendez.ortega@gmail.com"

      - name: 📝 CREANDO RELEASE
        uses: ./.github/actions/set-release
        with:
          releaseType: ":beta"
          branch: "main"
